/********************************************************************16**

            (c) Copyright 2012 by RadiSys Corporation. All rights reserved.

     This software is confidential and proprietary to RadiSys Corporation.
     No part of this software may be reproduced, stored, transmitted, 
     disclosed or used in any form or by any means other than as expressly
     provided by the written Software License Agreement between Radisys 
     and its licensee.

     Radisys warrants that for a period, as provided by the written
     Software License Agreement between Radisys and its licensee, this
     software will perform substantially to Radisys specifications as
     published at the time of shipment, exclusive of any updates or 
     upgrades, and the media used for delivery of this software will be 
     free from defects in materials and workmanship.  Radisys also warrants 
     that has the corporate authority to enter into and perform under the 
     Software License Agreement and it is the copyright owner of the software 
     as originally delivered to its licensee.

     RADISYS MAKES NO OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
     WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY OR FITNESS FOR
     A PARTICULAR PURPOSE WITH REGARD TO THIS SOFTWARE, SERVICE OR ANY RELATED
     MATERIALS.

     IN NO EVENT SHALL RADISYS BE LIABLE FOR ANY INDIRECT, SPECIAL,
     CONSEQUENTIAL DAMAGES, OR PUNITIVE DAMAGES IN CONNECTION WITH OR ARISING
     OUT OF THE USE OF, OR INABILITY TO USE, THIS SOFTWARE, WHETHER BASED
     ON BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT
     LIABILITY, OR OTHERWISE, AND WHETHER OR NOT IT HAS BEEN ADVISED
     OF THE POSSIBILITY OF SUCH DAMAGE.

                       Restricted Rights Legend:

     This software and all related materials licensed hereby are
     classified as "restricted computer software" as defined in clause
     52.227-19 of the Federal Acquisition Regulation ("FAR") and were
     developed entirely at private expense for nongovernmental purposes,
     are commercial in nature and have been regularly used for
     nongovernmental purposes, and, to the extent not published and
     copyrighted, are trade secrets and confidential and are provided
     with all rights reserved under the copyright laws of the United
     States.  The government's rights to the software and related
     materials are limited and restricted as provided in clause
     52.227-19 of the FAR.

                    IMPORTANT LIMITATION(S) ON USE

     The use of this software is limited to the use set
     forth in the written Software License Agreement between Radisys and
     its Licensee. Among other things, the use of this software
     may be limited to a particular type of Designated Equipment, as 
     defined in such Software License Agreement.
     Before any installation, use or transfer of this software, please
     consult the written Software License Agreement or contact Radisys at
     the location set forth below in order to confirm that you are
     engaging in a permissible use of the software.

                    RadiSys Corporation
                    Tel: +1 (858) 882 8800
                    Fax: +1 (858) 777 3388
                    Email: support@trillium.com
                    Web: http://www.radisys.com 
 
*********************************************************************17*/

/********************************************************************20**

     Name:     EnodeB Application

     Type:     C include file

     Desc:     This file contains 
               

     File:     wr_kpiIds.h

     Sid:      $SID$ 

     Prg:      Sriky 

*********************************************************************21*/
#ifndef __WR_KPIIDS_H__
#define __WR_KPIIDS_H__

#ifdef __cplusplus
extern "C" {
#endif /* end of __cplusplus */


/**
 * !!!!!! BIG IMPORTANT NOTE !!!!!!
 *
 * It's imperative that these enum values don't change.
 * Any new IDs must be added to the end.
 * This is because KPI IDs are written to the KPI log file and any new
 * revision of s/w must be able to read and correctly interpret old KPIs.
 */
typedef enum
{
#ifdef THREE_G_KPI /*3G KPI*/
    KPI_ID_BEGIN = 0,
    KPI_ID_ATTEMPTED_RAB_EST_CS_VOICE = KPI_ID_BEGIN,
    KPI_ID_ATTEMPTED_RAB_EST_CS_VIDEO,
    KPI_ID_ATTEMPTED_RAB_EST_CS_STREAMING,
    KPI_ID_ATTEMPTED_RAB_EST_PS_CONVERSATIONAL,
    KPI_ID_ATTEMPTED_RAB_EST_PS_INTERACTIVE,
    KPI_ID_ATTEMPTED_RAB_EST_PS_BACKGROUND,
    KPI_ID_ATTEMPTED_RAB_EST_PS_STREAMING,

    KPI_ID_SUCCESSFUL_RAB_EST_CS_VOICE,
    KPI_ID_SUCCESSFUL_RAB_EST_CS_VIDEO,
    KPI_ID_SUCCESSFUL_RAB_EST_CS_STREAMING,
    KPI_ID_SUCCESSFUL_RAB_EST_PS_CONVERSATIONAL,
    KPI_ID_SUCCESSFUL_RAB_EST_PS_INTERACTIVE,
    KPI_ID_SUCCESSFUL_RAB_EST_PS_BACKGROUND,
    KPI_ID_SUCCESSFUL_RAB_EST_PS_STREAMING,

    KPI_ID_RAB_RELEASE_CS_NORMAL,
    KPI_ID_RAB_RELEASE_CS_UTRAN,
    KPI_ID_RAB_RELEASE_CS_CN,
    KPI_ID_RAB_RELEASE_CS_OTHER,
    KPI_ID_RAB_RELEASE_PS_NORMAL,
    KPI_ID_RAB_RELEASE_PS_UTRAN,
    KPI_ID_RAB_RELEASE_PS_CN,
    KPI_ID_RAB_RELEASE_PS_OTHER,

    KPI_ID_ATTEMPTED_IU_SIG_CONN_EST_CS,
    KPI_ID_ATTEMPTED_IU_SIG_CONN_EST_PS,

    KPI_ID_SUCCESSFUL_IU_SIG_CONN_EST_CS,
    KPI_ID_SUCCESSFUL_IU_SIG_CONN_EST_PS,

    KPI_ID_IU_RELEASE_CMD_CS_NORMAL,
    KPI_ID_IU_RELEASE_CMD_CS_UTRAN,
    KPI_ID_IU_RELEASE_CMD_CS_CN,
    KPI_ID_IU_RELEASE_CMD_CS_OTHER,
    KPI_ID_IU_RELEASE_CMD_PS_NORMAL,
    KPI_ID_IU_RELEASE_CMD_PS_UTRAN,
    KPI_ID_IU_RELEASE_CMD_PS_CN,
    KPI_ID_IU_RELEASE_CMD_PS_OTHER,

    KPI_ID_ATTEMPTED_RB_EST_R99,
    KPI_ID_ATTEMPTED_RB_EST_HSDPA,
    KPI_ID_ATTEMPTED_RB_EST_HSUPA,

    KPI_ID_IU_RELEASE_REQ_CS_NORMAL,
    KPI_ID_IU_RELEASE_REQ_CS_UTRAN,
    KPI_ID_IU_RELEASE_REQ_CS_CN,
    KPI_ID_IU_RELEASE_REQ_CS_OTHER,
    KPI_ID_IU_RELEASE_REQ_PS_NORMAL,
    KPI_ID_IU_RELEASE_REQ_PS_UTRAN,
    KPI_ID_IU_RELEASE_REQ_PS_CN,
    KPI_ID_IU_RELEASE_REQ_PS_OTHER,

    KPI_ID_SUCCESSFUL_RB_EST_R99,
    KPI_ID_SUCCESSFUL_RB_EST_HSDPA,
    KPI_ID_SUCCESSFUL_RB_EST_HSUPA,

    KPI_ID_UNSUCCESSFUL_RB_EST_R99_PHY_FAILURE,
    KPI_ID_UNSUCCESSFUL_RB_EST_R99_PROTO_ERROR,
    KPI_ID_UNSUCCESSFUL_RB_EST_R99_CELL_UPDATE,
    KPI_ID_UNSUCCESSFUL_RB_EST_R99_CONFIG_FAILURE,
    KPI_ID_UNSUCCESSFUL_RB_EST_R99_NO_REPLY,
    KPI_ID_UNSUCCESSFUL_RB_EST_R99_OTHER_CAUSE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSDPA_PHY_FAILURE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSDPA_PROTO_ERROR,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSDPA_CELL_UPDATE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSDPA_CONFIG_FAILURE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSDPA_NO_REPLY,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSDPA_OTHER_CAUSE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSUPA_PHY_FAILURE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSUPA_PROTO_ERROR,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSUPA_CELL_UPDATE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSUPA_CONFIG_FAILURE,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSUPA_NO_REPLY,
    KPI_ID_UNSUCCESSFUL_RB_EST_HSUPA_OTHER_CAUSE,

    KPI_ID_ATTEMPTED_ACCESS_CONTROL_AUTH,
    KPI_ID_UNSUCCESSFUL_ACCESS_CONTROL_AUTH,

    KPI_ID_ATTEMPTED_RRC_CONN_EST,
    KPI_ID_SUCCESSFUL_RRC_CONN_EST,
    KPI_ID_UNSUCCESSFUL_RRC_CONN_EST_CONGESTION,
    KPI_ID_UNSUCCESSFUL_RRC_CONN_EST_UNSPECIFIED,
    KPI_ID_UNSUCCESSFUL_RRC_CONN_EST_NO_REPLY,
    KPI_ID_UNSUCCESSFUL_RRC_CONN_EST_OTHER_CAUSE,

    KPI_ID_MACRO_CELL_DETECTION_NONE,
    KPI_ID_MACRO_CELL_DETECTION_ONE_OR_MORE,

    KPI_ID_IU_USER_DATA_VOLUME_CS_UPLINK_KB,
    KPI_ID_IU_USER_DATA_VOLUME_CS_DOWNLINK_KB,
    KPI_ID_IU_USER_DATA_VOLUME_PS_UPLINK_KB,
    KPI_ID_IU_USER_DATA_VOLUME_PS_DOWNLINK_KB,

    /*KPI_ID_UNSUCCESSFUL_RAB_EST_*
    //KPI_ID_IU_RELEASE_REQ_*
    //KPI_ID_NUM_TXD_RLC_PDUS_*
    //KPI_ID_NUM_RETXD_RLC_PDUS_*
    //KPI_ID_MEAN_RLC_USER_DATA_THROUGHPUT_*
    //KPI_ID_UPLINK_BLOCK_ERROR_RATE_*
    //KPI_ID_IU_USER_DATA_VOLUME_**/
    KPI_ID_ATTEMPTED_RRC_CONN_REEST,
    KPI_ID_SUCCESSFUL_RRC_CONN_REEST,
    KPI_ID_UNSUCCESSFUL_RRC_CONN_REEST,
    KPI_ID_CELL_UPDATE,
    /*KPI_ID_ATTEMPTED_ACCESS_CONTROL_AUTH_**/
    KPI_ID_ATTEMPTED_ACCESS_CONTROL_TRIGGERED_RELOC,
    KPI_ID_ATTEMPTED_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT,
    KPI_ID_ATTEMPTED_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT,
    KPI_ID_SUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT,
    KPI_ID_SUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT_T_RELOC_PREP_EXPIRY,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT_RELOC_CANCELLED,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT_RELOC_FAILURE,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT_NO_REPLY,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTER_RAT_OTHER,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT_T_RELOC_PREP_EXPIRY,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT_RELOC_CANCELLED,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT_RELOC_FAILURE,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT_NO_REPLY,
    KPI_ID_UNSUCCESSFUL_RELOC_PREP_OUTGOING_HANDOVER_INTRA_RAT_OTHER,
    KPI_ID_ATTEMPTED_OUTGOING_HANDOVER_INTER_RAT_CS,
    KPI_ID_ATTEMPTED_OUTGOING_HANDOVER_INTER_RAT_PS,
    KPI_ID_ATTEMPTED_OUTGOING_HANDOVER_INTRA_RAT_CS,
    KPI_ID_ATTEMPTED_OUTGOING_HANDOVER_INTRA_RAT_PS,
    KPI_ID_SUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_CS,
    KPI_ID_SUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_PS,
    KPI_ID_SUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_CS,
    KPI_ID_SUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_PS,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_CS_CONFIG_UNACCEPTABLE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_CS_PHY_CHANNEL_FAILURE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_CS_PROTOCOL_ERROR,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_CS_OTHER,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_PS_CONFIG_UNACCEPTABLE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_PS_PHY_CHANNEL_FAILURE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_PS_PROTOCOL_ERROR,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTER_RAT_PS_OTHER,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_CS_CONFIG_UNACCEPTABLE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_CS_PHY_CHANNEL_FAILURE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_CS_PROTOCOL_ERROR,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_CS_OTHER,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_PS_CONFIG_UNACCEPTABLE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_PS_PHY_CHANNEL_FAILURE,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_PS_PROTOCOL_ERROR,
    KPI_ID_UNSUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_PS_OTHER,
    KPI_ID_ATTEMPTED_OUTGOING_HANDOVER_INTRA_RAT_INTRA_FREQ,
    KPI_ID_SUCCESSFUL_OUTGOING_HANDOVER_INTRA_RAT_INTRA_FREQ,
    /*KPI_ID_IP_RECONNECTIONS_**/
    KPI_ID_IP_LAYER_OCTETS_TX,
    KPI_ID_IP_LAYER_OCTETS_RX,

    KPI_ID_FAILED_RAB_EST_CS_INT,
    KPI_ID_FAILED_RAB_EST_CS_INT_MSG,
    KPI_ID_FAILED_RAB_EST_CS_PARAM,
    KPI_ID_FAILED_RAB_EST_CS_TRANS,
    KPI_ID_FAILED_RAB_EST_CS_NO_RSC,
    KPI_ID_FAILED_RAB_EST_CS_OTHER,
    KPI_ID_FAILED_RAB_EST_PS_INT,
    KPI_ID_FAILED_RAB_EST_PS_INT_MSG,
    KPI_ID_FAILED_RAB_EST_PS_PARAM,
    KPI_ID_FAILED_RAB_EST_PS_TRANS,
    KPI_ID_FAILED_RAB_EST_PS_NO_RSC,
    KPI_ID_FAILED_RAB_EST_PS_RELOC,
    KPI_ID_FAILED_RAB_EST_PS_OTHER,

    /*
    // Always add new IDs here, not before any existing ones!!  See note above.
    */

    KPI_ID_SUCCESSFUL_ACCESS_CONTROL_AUTH,
    KPI_ID_ATTEMPTED_ACCESS_CONTROL_ID,
    KPI_ID_SUCCESSFUL_ACCESS_CONTROL_ID,
    KPI_ID_3G_END,
#endif/*3G KPI*/
    KPI_ID_LTE_BEGIN, 
    /*LTE KPI begins from here*/
    KPI_ID_LTE_RRC_ATTCONESTAB_EMERGENCY = KPI_ID_LTE_BEGIN,
    KPI_ID_LTE_RRC_ATTCONESTAB_HIGHPRIORITYACCES, 
    KPI_ID_LTE_RRC_ATTCONESTAB_MTACCESS,
    KPI_ID_LTE_RRC_ATTCONESTAB_MOSIGNALLING,
    KPI_ID_LTE_RRC_ATTCONESTAB_MODATA,
    KPI_ID_LTE_RRC_ATTCONESTAB_DE_TO_ACCESS,
    KPI_ID_LTE_RRC_ATTCONESTAB_SUM,
    KPI_ID_LTE_RRC_SUCCCONESTAB_EMERGENCY,
    KPI_ID_LTE_RRC_SUCCCONESTAB_HIGHPRIORITYACCES,
    KPI_ID_LTE_RRC_SUCCCONESTAB_MTACCESS,
    KPI_ID_LTE_RRC_SUCCCONESTAB_MOSIGNALLING,
    KPI_ID_LTE_RRC_SUCCCONESTAB_MODATA,
    KPI_ID_LTE_RRC_SUCCCONESTAB_DE_TO_ACCESS,
    KPI_ID_LTE_RRC_SUCCCONNESTAB_SUM,
    KPI_ID_LTE_RRC_FAILCONESTAB_EMERGENCY,
    KPI_ID_LTE_RRC_FAILCONESTAB_HIGHPRIORITYACCES,
    KPI_ID_LTE_RRC_FAILCONESTAB_MTACCESS,
    KPI_ID_LTE_RRC_FAILCONESTAB_MOSIGNALLING,
    KPI_ID_LTE_RRC_FAILCONESTAB_MODATA,
    KPI_ID_LTE_RRC_FAILCONESTAB_DE_TO_ACCESS,
    KPI_ID_LTE_RRC_FAILCONNESTAB_SUM,
    KPI_ID_LTE_RRC_FAILCONESTAB_DEGRADEDRADIO_EMERGENCY,
    KPI_ID_LTE_RRC_FAILCONESTAB_DEGRADEDRADIO_HIGHPRIORITYACCES,
    KPI_ID_LTE_RRC_FAILCONESTAB_DEGRADEDRADIO_MTACCESS,
    KPI_ID_LTE_RRC_FAILCONESTAB_DEGRADEDRADIO_MOSIGNALLING,
    KPI_ID_LTE_RRC_FAILCONESTAB_DEGRADEDRADIO_MODATA,
    KPI_ID_LTE_RRC_FAILCONESTAB_DEGRADEDRADIO_DE_TO_ACCESS,
    KPI_ID_LTE_RRC_FAILCONNESTAB_DEGRADEDRADIO_SUM,
    KPI_ID_LTE_RRC_CONNREESTABATT_RECONF_FAIL,
    KPI_ID_LTE_RRC_CONNREESTABATT_HO_FAIL,
    KPI_ID_LTE_RRC_CONNREESTABATT_OTHER,
    KPI_ID_LTE_RRC_CONNREESTABATT_SUM,
    KPI_ID_LTE_RRC_CONNREESTABSUCC_RECONF_FAIL,
    KPI_ID_LTE_RRC_CONNREESTABSUCC_HO_FAIL,
    KPI_ID_LTE_RRC_CONNREESTABSUCC_OTHER,
    KPI_ID_LTE_RRC_CONNREESTABSUCC_SUM,
    KPI_ID_LTE_RRC_CONNREESTABFAIL_RECONF_FAIL,
    KPI_ID_LTE_RRC_CONNREESTABFAIL_HO_FAIL,
    KPI_ID_LTE_RRC_CONNREESTABFAIL_OTHER,
    KPI_ID_LTE_RRC_CONNREESTABFAIL_SUM,
    KPI_ID_LTE_RRC_CONNMEAN,
    KPI_ID_LTE_RRC_CONNMAX,
    KPI_ID_LTE_RRC_CONNESTABTIMEMEAN_EMERGENCY,
    KPI_ID_LTE_RRC_CONNESTABTIMEMEAN_HIGHPRIORITYACCESS,
    KPI_ID_LTE_RRC_CONNESTABTIMEMEAN_MTACCESS,
    KPI_ID_LTE_RRC_CONNESTABTIMEMEAN_MOSIGNALLING,
    KPI_ID_LTE_RRC_CONNESTABTIMEMEAN_MODATA,
    KPI_ID_LTE_RRC_CONNESTABTIMEMEAN_DELAYTOLACCESS,
    KPI_ID_LTE_RRC_CONNESTABTIMEMAX_EMERGENCY,
    KPI_ID_LTE_RRC_CONNESTABTIMEMAX_HIGHPRIORITYACCESS,
    KPI_ID_LTE_RRC_CONNESTABTIMEMAX_MTACCESS,
    KPI_ID_LTE_RRC_CONNESTABTIMEMAX_MOSIGNALLING,
    KPI_ID_LTE_RRC_CONNESTABTIMEMAX_MODATA,
    KPI_ID_LTE_RRC_CONNESTABTIMEMAX_DELAYTOLACCESS,
    KPI_ID_LTE_UECNTX_RELREQ_SUM,
    KPI_ID_LTE_UECONTEXT_RELSUCCNBR,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI1,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI2,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI3,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI4,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI5,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI6,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI7,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI8,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI9,
    KPI_ID_LTE_ERAB_ESTABINITATTNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI1,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI2,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI3,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI4,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI5,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI6,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI7,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI8,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI9,
    KPI_ID_LTE_ERAB_ESTABINITSUCCNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_ESTABINITFAILNBR_SUM,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI1,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI2,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI3,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI4,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI5,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI6,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI7,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI8,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI9,
    KPI_ID_LTE_ERAB_ESTABATTNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI1,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI2,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI3,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI4,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI5,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI6,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI7,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI8,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI9,
    KPI_ID_LTE_ERAB_ESTABSUCCNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_RADIORESOURCESNOTAVAILABLE,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_FAILUREINRADIOINTERFACEPROCEDURE,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_INVALIDQOSCOMBINATIONS,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_MULTIPLEERABIDINSTANCES,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_NOTSUPPORTEDQCIVALUE,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_S1INTRASYSTEMHANDOVERTRIGGERED,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_S1INTERSYSTEMHANDOVERTRIGGERED,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_X2HANDOVERTRIGGERED,
    KPI_ID_LTE_ERAB_ESTABFAILNBR_SUM,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI1,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI2,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI3,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI4,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI5,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI6,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI7,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI8,
    KPI_ID_LTE_ERAB_ESTABTIMEMEAN_QCI9,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI1,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI2,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI3,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI4,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI5,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI6,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI7,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI8,
    KPI_ID_LTE_ERAB_ESTABTIMEMAX_QCI9,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI1,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI2,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI3,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI4,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI5,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI6,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI7,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI8,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI9,
    KPI_ID_LTE_ERAB_RELENBNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_RELENBNBR_RADIORESOURCESNOTAVAILABLE,
    KPI_ID_LTE_ERAB_RELENBNBR_REDUCELOADINSERVINGCELL,
    KPI_ID_LTE_ERAB_RELENBNBR_FAILUREINTHERADIOINTERFACEPROCEDURE,
    KPI_ID_LTE_ERAB_RELENBNBR_RELEASEDUETOEUTRANGENERATEDREASONS,
    KPI_ID_LTE_ERAB_RELENBNBR_USERINACTIVITY,
    KPI_ID_LTE_ERAB_RELENBNBR_RADIOCONNECTIONWITHUELOST,
    KPI_ID_LTE_ERAB_RELENBNBR_OAMINTERVENTION,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI1,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI2,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI3,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI4,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI5, 
    KPI_ID_LTE_ERAB_RELATTNBR_QCI6,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI7,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI8,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI9,
    KPI_ID_LTE_ERAB_RELATTNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI1,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI2,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI3,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI4,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI5,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI6,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI7,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI8,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI9,
    KPI_ID_LTE_ERAB_RELSUCCNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_RELFAILNBR_UNKNOWNERABID,
    KPI_ID_LTE_ERAB_RELFAILNBR_HOFAILUREINTARGETSYSTEM,
    KPI_ID_LTE_ERAB_RELFAILNBR_UNKNOWNAREALREADYALLOCATEDMMEUES1APID,
    KPI_ID_LTE_ERAB_RELFAILNBR_UNKNOWNAREALREADYALLOCATEDENBUES1APID,
    KPI_ID_LTE_ERAB_RELFAILNBR_SUM,
    KPI_ID_LTE_ERAB_RELACTNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI1,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI2,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI3,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI4,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI5,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI6,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI7,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI8,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI9,
    KPI_ID_LTE_ERAB_MODQOSATTNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI1,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI2,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI3,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI4,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI5,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI6,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI7,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI8,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI9,
    KPI_ID_LTE_ERAB_MODQOSSUCCNBR_QCI_SUM,
    KPI_ID_LTE_ERAB_MODQOSFAILNBR_UNKNOWNERABID,
    KPI_ID_LTE_ERAB_MODQOSFAILNBR_MULTIPLEERABIDINSTANCES,
    KPI_ID_LTE_ERAB_MODQOSFAILNBR_RADIORESOURCESNOTAVAILABLE,
    KPI_ID_LTE_ERAB_MODQOSFAILNBR_FAILUREINTHERADIOINTERFACEPROCEDURE,
    KPI_ID_LTE_ERAB_MODQOSFAILNBR_INVALIDQOSCOMBINATION,
    KPI_ID_LTE_ERAB_MODQOSFAILNBR_SUM,
    KPI_ID_LTE_ERAB_SESSIONTIMEUE,
    KPI_ID_LTE_ERAB_USAGENBRMEAN_QCI_SUM,
    KPI_ID_LTE_ERAB_USAGENBRMAX_QCI_SUM,
    KPI_ID_LTE_HO_TOENBATT_SUM,   /*sum of Attempted outgoing handover to eNB   */
    KPI_ID_LTE_HO_TOENBSUCC_SUM,  /*sum of Successful outgoing handover to eNB  */
    KPI_ID_LTE_HO_TOENBFAIL_SUM,  /*sum of Failed outgoing handover to eNB      */
    KPI_ID_LTE_HO_FROMENBATT_SUM, /*sum of Attempted incoming handover from eNB */
    KPI_ID_LTE_HO_FROMENBSUCC_SUM,/*sum of Successful incoming handover from eNB*/
    KPI_ID_LTE_HO_FROMENBFAIL_SUM,/*sum of Failed incoming handover from eNB    */
    KPI_ID_LTE_HO_S1_BASED_HANDOUT_SUCC_SUM,
    KPI_ID_LTE_HO_S1_BASED_HANDIN_SUCC_SUM,
    KPI_ID_LTE_HO_TOUTRANATT_TOUTRANCELL_SUM,
    KPI_ID_LTE_HO_TOUTRANSUCC_TOUTRANCELL_SUM,
    KPI_ID_LTE_HO_TOUTRANFAIL_TOUTRANCELL_SUM,
    KPI_ID_LTE_HO_TOGERANATT_TOGERANCELL_SUM,
    KPI_ID_LTE_HO_TOGERANSUCC_TOGERANCELL_SUM,
    KPI_ID_LTE_HO_TOGERANFAIL_TOGERANCELL_SUM,
    KPI_ID_LTE_HO_INTERENBOUTPREPATT,
    KPI_ID_LTE_HO_INTRAFREQOUTATT,
    KPI_ID_LTE_HO_INTRAFREQOUTSUCC,
    KPI_ID_LTE_HO_INTERFREQMEASGAPOUTATT,
    KPI_ID_LTE_HO_INTERFREQMEASGAPOUTSUCC,
    KPI_ID_LTE_HO_INTERFREQNOMEASGAPOUTATT,
    KPI_ID_LTE_HO_INTERFREQNOMEASGAPOUTSUCC,
    KPI_ID_LTE_HO_DRXOUTATT,
    KPI_ID_LTE_HO_DRXOUTSUCC,
    KPI_ID_LTE_HO_NODRXOUTATT,
    KPI_ID_LTE_HO_NODRXOUTSUCC,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI1,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI2,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI3,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI4,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI5,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI6,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI7,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI8,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI9,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDL_QCI_SUM,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEDLMAX,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI1,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI2,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI3,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI4,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI5,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI6,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI7,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI8,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI9,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEUL_QCI_SUM,
    KPI_ID_LTE_DRB_PDCPSDUBITRATEULMAX,
    KPI_ID_LTE_SRB_PDCPSDUBITRATEDL,
    KPI_ID_LTE_SRB_PDCPSDUBITRATEUL,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI1,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI2,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI3,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI4,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI5,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI6,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI7,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI8,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI9,
    KPI_ID_LTE_DRB_PDCPSDUDELAYDL_QCI_SUM,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI1,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI2,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI3,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI4,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI5,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI6,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI7,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI8,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI9,
    KPI_ID_LTE_DRB_PDCPSDUDROPRATEDL_QCI_SUM,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI1,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI2,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI3,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI4,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI5,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI6,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI7,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI8,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI9,
    KPI_ID_LTE_DRB_PDCPSDUAIRLOSSRATEDL_QCI_SUM,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI1,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI2,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI3,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI4,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI5,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI6,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI7,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI8,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI9,
    KPI_ID_LTE_DRB_PDCPSDULOSSRATEUL_QCI_SUM,
    KPI_ID_LTE_DRB_IPTHPDL_QCI1,
    KPI_ID_LTE_DRB_IPTHPDL_QCI2,
    KPI_ID_LTE_DRB_IPTHPDL_QCI3,
    KPI_ID_LTE_DRB_IPTHPDL_QCI4,
    KPI_ID_LTE_DRB_IPTHPDL_QCI5,
    KPI_ID_LTE_DRB_IPTHPDL_QCI6,
    KPI_ID_LTE_DRB_IPTHPDL_QCI7,
    KPI_ID_LTE_DRB_IPTHPDL_QCI8,
    KPI_ID_LTE_DRB_IPTHPDL_QCI9,
    KPI_ID_LTE_DRB_IPTHPUL_QCI1,
    KPI_ID_LTE_DRB_IPTHPUL_QCI2,
    KPI_ID_LTE_DRB_IPTHPUL_QCI3,
    KPI_ID_LTE_DRB_IPTHPUL_QCI4,
    KPI_ID_LTE_DRB_IPTHPUL_QCI5,
    KPI_ID_LTE_DRB_IPTHPUL_QCI6,
    KPI_ID_LTE_DRB_IPTHPUL_QCI7,
    KPI_ID_LTE_DRB_IPTHPUL_QCI8,
    KPI_ID_LTE_DRB_IPTHPUL_QCI9,
    KPI_ID_LTE_RRU_PRBDL_QCI1,
    KPI_ID_LTE_RRU_PRBDL_QCI2,
    KPI_ID_LTE_RRU_PRBDL_QCI3,
    KPI_ID_LTE_RRU_PRBDL_QCI4,
    KPI_ID_LTE_RRU_PRBDL_QCI5,
    KPI_ID_LTE_RRU_PRBDL_QCI6,
    KPI_ID_LTE_RRU_PRBDL_QCI7,
    KPI_ID_LTE_RRU_PRBDL_QCI8,
    KPI_ID_LTE_RRU_PRBDL_QCI9,
    KPI_ID_LTE_RRU_PRBDL_QCI_SUM,
    KPI_ID_LTE_RRU_PRBTOTDL,
    KPI_ID_LTE_RRU_PRBUL_QCI1,
    KPI_ID_LTE_RRU_PRBUL_QCI2,
    KPI_ID_LTE_RRU_PRBUL_QCI3,
    KPI_ID_LTE_RRU_PRBUL_QCI4,
    KPI_ID_LTE_RRU_PRBUL_QCI5,
    KPI_ID_LTE_RRU_PRBUL_QCI6,
    KPI_ID_LTE_RRU_PRBUL_QCI7,
    KPI_ID_LTE_RRU_PRBUL_QCI8,
    KPI_ID_LTE_RRU_PRBUL_QCI9,
    KPI_ID_LTE_RRU_PRBUL_QCI_SUM,
    KPI_ID_LTE_RRU_PRBTOTUL,
    KPI_ID_LTE_RRU_RACHPREAMBLEDEDMEAN,
    KPI_ID_LTE_RRU_RACHPREAMBLEAMEAN,
    KPI_ID_LTE_RRU_RACHPREAMBLEBMEAN,


    KPI_ID_LTE_RRU_CELLUNAVAILABLETIME_MANUALINTERVENTION,
    KPI_ID_LTE_RRU_CELLUNAVAILABLETIME_FAULT,
    KPI_ID_LTE_RRU_CELLUNAVAILABLETIME_SUM,
    KPI_ID_LTE_S1SIG_CONNESTABATT,
    KPI_ID_LTE_S1SIG_CONNESTABSUCC,
    KPI_ID_LTE_PAG_DISCARDEDNBR,
    KPI_ID_LTE_CSG_ATTINBOUNDMOBILITY,
    KPI_ID_LTE_CSG_SUCCINBOUNDMOBILITY,
    KPI_ID_LTE_CSG_FAILEDINBOUNDMOBILITY_SUM,
    KPI_ID_LTE_CSG_UEATTACHED_MEAN,
    KPI_ID_LTE_EQPT_MEANPROCESSORUSAGE_PROCESSORID,
    KPI_ID_LTE_EQPT_PEAKPROCESSORUSAGE_PROCESSORID,
    KPI_ID_LTE_CFR_S1AP_RN_00, 
    KPI_ID_LTE_CFR_S1AP_RN_01, 
    KPI_ID_LTE_CFR_S1AP_RN_02, 
    KPI_ID_LTE_CFR_S1AP_RN_03, 
    KPI_ID_LTE_CFR_S1AP_RN_04, 
    KPI_ID_LTE_CFR_S1AP_RN_05, 
    KPI_ID_LTE_CFR_S1AP_RN_06, 
    KPI_ID_LTE_CFR_S1AP_RN_07, 
    KPI_ID_LTE_CFR_S1AP_RN_08, 
    KPI_ID_LTE_CFR_S1AP_RN_09, 
    KPI_ID_LTE_CFR_S1AP_RN_10, 
    KPI_ID_LTE_CFR_S1AP_RN_11, 
    KPI_ID_LTE_CFR_S1AP_RN_12, 
    KPI_ID_LTE_CFR_S1AP_RN_13, 
    KPI_ID_LTE_CFR_S1AP_RN_14, 
    KPI_ID_LTE_CFR_S1AP_RN_15, 
    KPI_ID_LTE_CFR_S1AP_RN_16, 
    KPI_ID_LTE_CFR_S1AP_RN_17, 
    KPI_ID_LTE_CFR_S1AP_RN_18, 
    KPI_ID_LTE_CFR_S1AP_RN_19, 
    KPI_ID_LTE_CFR_S1AP_RN_20, 
    KPI_ID_LTE_CFR_S1AP_RN_21, 
    KPI_ID_LTE_CFR_S1AP_RN_22, 
    KPI_ID_LTE_CFR_S1AP_RN_23, 
    KPI_ID_LTE_CFR_S1AP_RN_24, 
    KPI_ID_LTE_CFR_S1AP_RN_25, 
    KPI_ID_LTE_CFR_S1AP_RN_26, 
    KPI_ID_LTE_CFR_S1AP_RN_27, 
    KPI_ID_LTE_CFR_S1AP_RN_28, 
    KPI_ID_LTE_CFR_S1AP_RN_29, 
    KPI_ID_LTE_CFR_S1AP_RN_30, 
    KPI_ID_LTE_CFR_S1AP_RN_31, 
    KPI_ID_LTE_CFR_S1AP_RN_32, 
    KPI_ID_LTE_CFR_S1AP_RN_33, 
    KPI_ID_LTE_CFR_S1AP_RN_34, 
    KPI_ID_LTE_CFR_S1AP_RN_35, 
    KPI_ID_LTE_CFR_S1AP_RN_36, 
    KPI_ID_LTE_CFR_S1AP_RN_37, 
    KPI_ID_LTE_CFR_S1AP_RN_38, 
    KPI_ID_LTE_CFR_S1AP_TP_00,
    KPI_ID_LTE_CFR_S1AP_TP_01,
    KPI_ID_LTE_CFR_S1AP_NAS_00,
    KPI_ID_LTE_CFR_S1AP_NAS_01,
    KPI_ID_LTE_CFR_S1AP_NAS_02,
    KPI_ID_LTE_CFR_S1AP_NAS_03,
    KPI_ID_LTE_CFR_S1AP_NAS_04,
    KPI_ID_LTE_CFR_S1AP_PROT_00,
    KPI_ID_LTE_CFR_S1AP_PROT_01,
    KPI_ID_LTE_CFR_S1AP_PROT_02,
    KPI_ID_LTE_CFR_S1AP_PROT_03,
    KPI_ID_LTE_CFR_S1AP_PROT_04,
    KPI_ID_LTE_CFR_S1AP_PROT_05,
    KPI_ID_LTE_CFR_S1AP_PROT_06,
    KPI_ID_LTE_CFR_S1AP_MISC_00,
    KPI_ID_LTE_CFR_S1AP_MISC_01,
    KPI_ID_LTE_CFR_S1AP_MISC_02,
    KPI_ID_LTE_CFR_S1AP_MISC_03,
    KPI_ID_LTE_CFR_S1AP_MISC_04,
    KPI_ID_LTE_CFR_S1AP_MISC_05,
    KPI_ID_LTE_CFR_RRC_RRE_00,
    KPI_ID_LTE_CFR_RRC_RRE_01,
    KPI_ID_LTE_CFR_RRC_RRE_02,
    KPI_ID_LTE_CFR_RRC_RRE_03,
    KPI_ID_LTE_CFR_RRC_00,
    KPI_ID_LTE_CFR_RRC_01,
    KPI_ID_LTE_CFR_GTP_00,
    KPI_ID_LTE_CFR_GTP_01,
    KPI_ID_LTE_CFR_RLC_00,    
    KPI_ID_LTE_RRC_S1AP_FAIL_COUNT,
    KPI_ID_LTE_RRC_PDCP_FAIL_COUNT,
    KPI_ID_LTE_RRC_RLC_FAIL_COUNT,
    KPI_ID_LTE_RRC_MAC_FAIL_COUNT,
    KPI_ID_LTE_RRC_RRC_FAIL_COUNT,
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE1, /* Hand-out attempted with cause Time critical handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE2, /* Hand-out attempted with cause Handover desirable for Radio reasons */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE3, /* Hand-out attempted with cause Resource optimization handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE4, /* Hand-out attempted with cause Reduce load in serving cell */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE1,/* Hand-out Success with cause Time critical handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE2,/* Hand-out Success with cause Handover desirable for Radio reasons */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE3,/* Hand-out Success with cause Resource optimization handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE4,/* Hand-out Success with cause Reduce load in serving cell */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE1_PER_TGT_CELL, /* Hand-out attempted per cell with cause Time critical handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE2_PER_TGT_CELL, /* Hand-out attempted per cell with cause Handover desirable for Radio reasons */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE3_PER_TGT_CELL, /* Hand-out attempted per cell with cause Resource optimization handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_CAUSE4_PER_TGT_CELL, /* Hand-out attempted per cell with cause Reduce load in serving cell */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_ATT_SUM_PER_TGT_CELL,    /* Sum of Hand-out attempted per cell */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE1_PER_TGT_CELL,/* Hand-out Success per cell with cause Time critical handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE2_PER_TGT_CELL,/* Hand-out Success per cell with cause Handover desirable for Radio reasons */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE3_PER_TGT_CELL,/* Hand-out Success per cell with cause Resource optimization handover */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_CAUSE4_PER_TGT_CELL,/* Hand-out Success per cell with cause Reduce load in serving cell */
    KPI_ID_LTE_OUT_INTER_ENB_HO_EXE_SUCC_SUM_PER_TGT_CELL,   /* Sum of Hand-out Success per cell */
    
    KPI_ID_LTE_TB_TOT_NBR_DL,
    KPI_ID_LTE_TB_ERR_NBR_DL,
    KPI_ID_LTE_TB_TOT_NBR_UL,
    KPI_ID_LTE_TB_ERR_NBR_UL,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI1,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI2,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI3,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI4,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI5,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI6,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI7,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI8,
    KPI_ID_LTE_DRB_UE_ACT_DL_QCI9,
    KPI_ID_LTE_DRB_UE_ACT_DL_SUM,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI1,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI2,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI3,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI4,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI5,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI6,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI7,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI8,
    KPI_ID_LTE_DRB_UE_ACT_UL_QCI9,
    KPI_ID_LTE_DRB_UE_ACT_UL_SUM,
    KPI_ID_LTE_RRC_FAILCONESTAB_CONGESTION, /* Each transmitted RRCConnectionReject message caused by "congestion" is added to the measurement cause "Congestion" */
    KPI_ID_LTE_RRC_FAILCONESTAB_UNSPECIFIED,/* Each transmitted RRCConnectionReject message caused by the other reasons is added to measurement cause "Unspecified". */
    KPI_ID_LTE_CSFB_ATT_SUM, /* CSFB Attempted Sum */
    KPI_ID_LTE_CSFB_SUCC_SUM,/* CSFB Success Sum */
    KPI_ID_LTE_CSFB_FAIL_SUM, /* CSFB Fail Sum */
    KPI_ID_LTE_CSFB_UTRA_ATT_SUM, /*CSFB to UTRA attempts Sum */
    KPI_ID_LTE_CSFB_UTRA_SUCC_SUM, /* CSFB to UTRA  Success Sum */
    KPI_ID_LTE_CSFB_UTRA_FAIL_SUM, /*  CSFB to UTRA  failure sum */
    KPI_ID_LTE_CSFB_UTRA_WITH_REDIR_WITH_SI, /* Successful CSFB to UTRAN cell through RRCConnectionRelease with redirection with SI */
    KPI_ID_LTE_CSFB_UTRA_WITHOUT_REDIR, /* Successful CSFB to UTRAN cell through RRCConnectionRelease without redirection */
    KPI_ID_LTE_CSFB_CDMA2000_DUALRX_WO_REDIR,/* CSFB Dual Rx with-out Re-Direction */
    KPI_ID_LTE_CSFB_CDMA2000_REDIR, /* CSFB with Re-Direction */
    KPI_ID_LTE_CSFB_CDMA2000_WO_PSHO_SUCC,/* eCSFB or CSFB with-out PS HO */
    KPI_ID_LTE_CSFB_CDMA2000_WO_PSHO_FAIL,/* eCSFB or CSFB with-out PS HO */
    KPI_ID_LTE_CSFB_CDMA2000_WO_PSHO_ATT,/* eCSFB or CSFB with-out PS HO */
    KPI_ID_LTE_CSFB_CDMA2000_WO_PSHO_FAIL_REDIR_SUCC,/*eCSFB or CSFB with PSHO failure */
    /* Inter RAT Hand-out attempted with any one of cause */ 
    KPI_ID_LTE_INTER_RAT_UTRA_ATT_SUM,                 
    /* Inter RAT Hand-out success with any one of cause */ 
    KPI_ID_LTE_INTER_RAT_UTRA_SUCC_SUM,  
    /* Inter RAT Hand-out failure with any one of cause */     
    KPI_ID_LTE_INTER_RAT_UTRA_FAIL_SUM,
    /* Inter RAT Hand-out attempted with cause Time critical handover */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_ATT_CAUSE1,
    /* Inter RAT Hand-out attempted with cause Handover desirable for Radio reasons */     
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_ATT_CAUSE2,   
    /* Inter RAT Hand-out attempted with cause Resource optimization handover */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_ATT_CAUSE3,   
    /* Inter RAT Hand-out attempted with cause Reduce load in serving cell */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_ATT_CAUSE4,   
    /* Inter RAT Hand-out Success with cause Time critical handover */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_SUCC_CAUSE1,  
    /* Inter RAT Hand-out Success with cause Handover desirable for Radio reasons */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_SUCC_CAUSE2,  
    /* Inter RAT Hand-out Success with cause Resource optimization handover */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_SUCC_CAUSE3,  
    /* Inter RAT Hand-out Success with cause Reduce load in serving cell */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_SUCC_CAUSE4,  
    /* Inter RAT Hand-out Success with cause Time critical handover */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_FAIL_CAUSE1,  
    /* Inter RAT Hand-out Success with cause Handover desirable for Radio reasons */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_FAIL_CAUSE2,  
    /* Inter RAT Hand-out Success with cause Resource optimization handover */  
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_FAIL_CAUSE3,  
    /* Inter RAT Hand-out Success with cause Reduce load in serving cell */ 
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_HO_EXE_FAIL_CAUSE4, 
    /* RIM Procedure Attempts*/
    KPI_ID_LTE_RIM_PROC_ATT,
    /* RIM Procedure Success*/
    KPI_ID_LTE_RIM_PROC_SUCC,
    /* RIM Procedure Fail*/
    KPI_ID_LTE_RIM_PROC_FAIL, 
    KPI_ID_LTE_CSFB_GERAN_ATT_SUM,
    /* CSFB to GERAN attempted sum */
    KPI_ID_LTE_CSFB_GERAN_SUCC_SUM,
    /* CSFB to GERAN success sum */
    KPI_ID_LTE_CSFB_GERAN_REDIR,
    /* CSFB to GERAN successful with RRC Connection Release with redirection information */
    KPI_ID_LTE_CSFB_GERAN_CCO,
    /* CSFB to GERAN successful Cell Change Order */
    KPI_ID_LTE_CSFB_GERAN_FAIL,
    /* CSFB to GERAN procedure Failure */
    KPI_ID_LTE_IRAT_MOB_LAI_1,
    /* To keep track of number of incoming IRAT mobility events per LAI1 */
    KPI_ID_LTE_IRAT_MOB_LAI_2,
    /* To keep track of number of incoming IRAT mobility events per LAI2 */
    KPI_ID_LTE_IRAT_MOB_LAI_3,
    /* To keep track of number of incoming IRAT mobility events per LAI3 */
    KPI_ID_LTE_IRAT_MOB_LAI_4,
    /* To keep track of number of incoming IRAT mobility events per LAI4 */
    KPI_ID_LTE_IRAT_MOB_LAI_5,
    /* To keep track of number of incoming IRAT mobility events per LAI5 */
    KPI_ID_LTE_IRAT_MOB_LAI_6,
    /* To keep track of number of incoming IRAT mobility events per LAI6 */
    KPI_ID_LTE_IRAT_MOB_LAI_7,
    /* To keep track of number of incoming IRAT mobility events per LAI7 */
    KPI_ID_LTE_IRAT_MOB_LAI_8,
    /* To keep track of number of incoming IRAT mobility events per LAI8 */
    KPI_ID_LTE_IRAT_MOB_LAI_9,
    /* To keep track of number of incoming IRAT mobility events per LAI9 */
    KPI_ID_LTE_IRAT_MOB_LAI_10,
    /* To keep track of number of incoming IRAT mobility events per LAI10 */
    KPI_ID_LTE_IRAT_MOB_LAI_11,
    /* To keep track of number of incoming IRAT mobility events per LAI11 */
    KPI_ID_LTE_IRAT_MOB_LAI_12,
    /* To keep track of number of incoming IRAT mobility events per LAI12 */
    KPI_ID_LTE_IRAT_MOB_LAI_13,
    /* To keep track of number of incoming IRAT mobility events per LAI13 */
    KPI_ID_LTE_IRAT_MOB_LAI_14,
    /* To keep track of number of incoming IRAT mobility events per LAI14 */
    KPI_ID_LTE_IRAT_MOB_LAI_15,
    /* To keep track of number of incoming IRAT mobility events per LAI15 */
    KPI_ID_LTE_IRAT_MOB_LAI_16,
    /* To keep track of number of incoming IRAT mobility events per LAI16 */
    KPI_ID_LTE_IRAT_MOB_LAI_17,
    /* To keep track of number of incoming IRAT mobility events per LAI17 */
    KPI_ID_LTE_IRAT_MOB_LAI_18,
    /* To keep track of number of incoming IRAT mobility events per LAI18 */
    KPI_ID_LTE_IRAT_MOB_LAI_19,
    /* To keep track of number of incoming IRAT mobility events per LAI19 */
    KPI_ID_LTE_IRAT_MOB_LAI_20,
    /* To keep track of number of incoming IRAT mobility events per LAI20 */
    KPI_ID_LTE_IRAT_MOB_LAI_21,
    /* To keep track of number of incoming IRAT mobility events per LAI21 */
    KPI_ID_LTE_IRAT_MOB_LAI_22,
    /* To keep track of number of incoming IRAT mobility events per LAI22 */
    KPI_ID_LTE_IRAT_MOB_LAI_23,
    /* To keep track of number of incoming IRAT mobility events per LAI23 */
    KPI_ID_LTE_IRAT_MOB_LAI_24,
    /* To keep track of number of incoming IRAT mobility events per LAI24 */
    KPI_ID_LTE_IRAT_MOB_LAI_25,
    /* To keep track of number of incoming IRAT mobility events per LAI25 */
    KPI_ID_LTE_IRAT_MOB_LAI_26,
    /* To keep track of number of incoming IRAT mobility events per LAI26 */
    KPI_ID_LTE_IRAT_MOB_LAI_27,
    /* To keep track of number of incoming IRAT mobility events per LAI27 */
    KPI_ID_LTE_IRAT_MOB_LAI_28,
    /* To keep track of number of incoming IRAT mobility events per LAI28 */
    KPI_ID_LTE_IRAT_MOB_LAI_29,
    /* To keep track of number of incoming IRAT mobility events per LAI29 */
    KPI_ID_LTE_IRAT_MOB_LAI_30,
    /* To keep track of number of incoming IRAT mobility events per LAI30 */
    KPI_ID_LTE_IRAT_MOB_LAI_31,
    /* To keep track of number of incoming IRAT mobility events per LAI31 */
    KPI_ID_LTE_IRAT_MOB_LAI_32,
    /* To keep track of number of incoming IRAT mobility events per LAI32 */
    KPI_ID_LTE_IRAT_MOB_LAI_OTH,
    /* To keep track of number of incoming IRAT mobility events per LAIOTH */
    KPI_ID_LTE_CSFB_GERAN_CCO_WITH_NACC,
    /* CSFB to GERAN successful Cell Change Order with NACC */
    KPI_ID_LTE_CSFB_GERAN_REDIR_WITH_SI,
    /* Successful CSFB to GERAN through RRC Connection Release with redirection information along with SI */
    /* ccpu00141451 - counter to track successful HO via RRC Re-establishment */
    KPI_ID_LTE_HO_FROMENBSUCC_SUM_AFTR_REEST,

    /*RRC Rel10 Upgrade*/  
    /* Counter based on the number of times dual Rx/Tx eCSFB procedure is completed with redirection */
    KPI_ID_LTE_CSFB_CDMA2000_DUALRXTX_REDIR,
    /* Counter based on the number of times dual Rx/Tx eCSFB procedure is completed */
    KPI_ID_LTE_CSFB_CDMA2000_DUALRXTX_DLNAS,  
    /* Counter based on the number of times Full Reconfiguration executed for Handover procedure.*/
    KPI_ID_LTE_HO_FROMENB_FULL_RECFG, 
    /* Counter based on the number of times Full Reconfiguration executed for Re-Establishment procedure.*/
    KPI_ID_LTE_RRC_CONNREESTAB_FULL_RECFG, 
    /*RRC Rel10 Upgrade*/  
    KPI_ID_LTE_L3CPUSTATS_CORE0_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE1_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE2_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE3_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE4_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE5_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE6_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE7_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE8_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE9_AVG,
    KPI_ID_LTE_L3CPUSTATS_CORE0_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE1_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE2_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE3_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE4_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE5_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE6_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE7_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE8_MAX,
    KPI_ID_LTE_L3CPUSTATS_CORE9_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE0_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE1_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE2_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE3_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE4_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE5_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE6_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE7_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE8_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE9_AVG,
    KPI_ID_LTE_L2CPUSTATS_CORE0_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE1_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE2_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE3_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE4_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE5_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE6_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE7_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE8_MAX,
    KPI_ID_LTE_L2CPUSTATS_CORE9_MAX,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG0_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG1_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG2_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG3_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG4_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SSI_REG5_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUH_SHARED_REG_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG0_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG1_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG2_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG3_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG4_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SSI_REG5_POOL5_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL0_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL0_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL0_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL0_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL1_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL1_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL1_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL1_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL2_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL2_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL2_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL2_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL3_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL3_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL3_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL3_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL4_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL4_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL4_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL4_MAX_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL5_SIZE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL5_TOTAL_AVAILABLE,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL5_CRNT_USED,
    KPI_ID_LTE_MEMINFO_CPUL_SHARED_REG_POOL5_MAX_USED,
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_SRVCC_ATT_SUM,
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_SRVCC_SUCC_SUM,
    KPI_ID_LTE_OUT_INTER_RAT_UTRA_SRVCC_FAIL_SUM,
    KPI_ID_LTE_OUT_INTER_RAT_GERAN_SRVCC_ATT_SUM,
    KPI_ID_LTE_OUT_INTER_RAT_GERAN_SRVCC_SUCC_SUM,
    KPI_ID_LTE_OUT_INTER_RAT_GERAN_SRVCC_FAIL_SUM,
    NUM_KPIS,
    INVALID_KPI

} KpiId;
#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif/* ___KPIIdsH__*/


/********************************************************************30**

           End of file:    $SID$

*********************************************************************31*/


/********************************************************************40**
  
        Notes:
  
*********************************************************************41*/

/********************************************************************50**

*********************************************************************51*/

   
/********************************************************************60**
  
        Revision history:
  
*********************************************************************61*/
  
/********************************************************************90**
 
     ver       pat    init                  description
------------ -------- ---- ----------------------------------------------
$SID$        ---      Sriky         1. initial release TotaleNodeB 1.1
*********************************************************************91*/
